const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Behaviors.TileMovement,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Keyboard.Exps.TypedKey,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.TileMovement.Acts.SimulateControl,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{精靈: 0},
	{精靈2: 0},
	{正弦運動: 0},
	{Barrier: 0},
	{補間動畫: 0},
	{Explosion: 0},
	{Explosion2: 0},
	{TileMovement: 0},
	{Player: 0},
	{PlayerSpaceship: 0},
	{號碼: 0},
	{指令: 0},
	{提醒: 0},
	{精靈3: 0},
	{判定: 0},
	{文本: 0},
	{過熱狀態: 0},
	{鍵盤: 0},
	{顯示前動: 0},
	{展示機器人: 0},
	{音訊: 0},
	{移動次數: 0},
	{冷爆次數: 0},
	{前一動: 0},
	{前一號: 0},
	{可動狀態: 0},
	{結尾詞: 0},
	{編號儲存: 0},
	{讀取: 0}
];

self.InstanceType = {
	精靈: class extends self.ISpriteInstance {},
	精靈2: class extends self.ISpriteInstance {},
	Barrier: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Explosion2: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	PlayerSpaceship: class extends self.ISpriteInstance {},
	號碼: class extends self.ISpriteInstance {},
	指令: class extends self.ISpriteInstance {},
	提醒: class extends self.ISpriteInstance {},
	精靈3: class extends self.ISpriteInstance {},
	判定: class extends self.ITextInstance {},
	文本: class extends self.ITextInstance {},
	過熱狀態: class extends self.ITextInstance {},
	鍵盤: class extends self.IInstance {},
	顯示前動: class extends self.ITextInstance {},
	展示機器人: class extends self.ISpriteInstance {},
	音訊: class extends self.IInstance {}
}